#!/usr/bin/env python3
"""Render thesis/provenance-sweep.md from the frozen R-7 sweep rows.

    .venv-ft/bin/python thesis/make_provenance_sweep.py

Input is `thesis/provenance-sweep.json`, the verbatim return value of the six
R-7 audit agents (one entry per agent: its scope, how many numbers it found,
and one row per number it chose to report). The rows are frozen evidence - this
script never edits them, it only groups and formats. If a finding is later
fixed in the ledgers, record that in the FIXED table at the bottom of the
rendered doc rather than by mutating the JSON: the point of the sweep is to be
a dated audit, and an audit you can silently edit is not one.

Tags, as the agents were instructed to apply them:

  VERIFIED     the number reproduces from an artifact the agent opened
  MISLEADING   the number is right but its framing, units, denominator or
               machine attribution makes a reader draw the wrong conclusion
  CONTRADICTED an artifact exists and says something else
  UNVERIFIED   no artifact behind the number at all
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
SWEEP = HERE / "provenance-sweep.json"
RESOLUTIONS = HERE / "provenance-resolutions.json"
OUT = HERE / "provenance-sweep.md"

TAG_ORDER = ["CONTRADICTED", "UNVERIFIED", "MISLEADING", "VERIFIED"]
FILE_ORDER = [
    "README.md",
    "RESULTS.md",
    "docs/results/part1-exploratory.md",
    "docs/results/part2-rebuild.md",
    "docs/results/part3-permanence.md",
    "docs/results/part4-end-to-end.md",
    "docs/results/part5-anticipatory.md",
    "docs/results/part6-flight.md",
]


def esc(s: str) -> str:
    """Make a free-text field safe inside a markdown table cell."""
    return " ".join(str(s).split()).replace("|", "\\|")


def render() -> str:
    data = json.loads(SWEEP.read_text())
    agents = data["agents"]
    # Positional id, stable because the sweep rows are frozen (see r21_queue.py).
    rows = [dict(r, row_id=f"{ai}.{ri}")
            for ai, a in enumerate(agents) for ri, r in enumerate(a["rows"])]
    res = (json.loads(RESOLUTIONS.read_text())["resolutions"]
           if RESOLUTIONS.exists() else {})
    tags = Counter(r["tag"] for r in rows)
    n_found = sum(a["n_numbers_found"] for a in agents)

    L: list[str] = []
    add = L.append

    add("# Provenance sweep (R-7)")
    add("")
    add("Generated by `thesis/make_provenance_sweep.py` from `thesis/provenance-sweep.json`.")
    add("Do not edit this file by hand.")
    add("")
    add("Six audit agents swept `README.md`, `RESULTS.md` and the six per-Part result")
    add("ledgers on 2026-07-21, tracing every published number back to the artifact that")
    add("produced it. Each agent was required to *open* the artifact - a number is")
    add("`VERIFIED` only against a file the agent read, never against another prose")
    add("restatement of the same claim.")
    add("")
    add(f"**{n_found} numbers examined, {len(rows)} reported.** A number that reproduced")
    add("cleanly and carried no framing problem was counted and dropped; what is tabulated")
    add("below is every defect found, plus the load-bearing numbers the agents chose to")
    add("record as verified so the headline figures have a citable provenance row.")
    add("")
    add("| Tag | Rows | Meaning |")
    add("|---|---|---|")
    add(f"| CONTRADICTED | {tags['CONTRADICTED']} | an artifact exists and says something else |")
    add(f"| UNVERIFIED | {tags['UNVERIFIED']} | no artifact behind the number at all |")
    add(f"| MISLEADING | {tags['MISLEADING']} | value right, framing/units/denominator/machine wrong |")
    add(f"| VERIFIED | {tags['VERIFIED']} | reproduces from an opened artifact |")
    add("")
    add("The three non-VERIFIED tags are the work queue. They are not equally urgent:")
    add("a CONTRADICTED number is wrong in print, a MISLEADING one is a sentence that")
    add("has to be rewritten, an UNVERIFIED one needs a re-run or a deletion.")
    add("")
    if res:
        queue = [r for r in rows if r["tag"] in ("MISLEADING", "UNVERIFIED")]
        fixed = sum(1 for r in queue if res.get(r["row_id"], {}).get("status") == "fixed")
        acc = sum(1 for r in queue if res.get(r["row_id"], {}).get("status") == "accepted")
        add(f"**R-21 status: {fixed} rewritten in place, {acc} accepted with a stated")
        add(f"reason, {len(queue) - fixed - acc} still open** of {len(queue)} queued. Per-row")
        add("detail is in the Resolutions section at the bottom; the finding rows above are")
        add("left exactly as the agents wrote them, because a dated audit that gets edited")
        add("once its findings are fixed stops being evidence that they were ever there.")
        add("")

    add("## Scope covered")
    add("")
    for a in agents:
        add(f"- {esc(a['scope'])[:400]}")
    add("")

    for tag in TAG_ORDER:
        sel = [r for r in rows if r["tag"] == tag]
        if not sel:
            continue
        add(f"## {tag} ({len(sel)})")
        add("")
        for f in FILE_ORDER:
            fsel = [r for r in sel if r["file"] == f]
            if not fsel:
                continue
            add(f"### `{f}`")
            add("")
            add("| Published | Claim | Artifact | What the artifact says | Finding |")
            add("|---|---|---|---|---|")
            for r in fsel:
                add(
                    f"| {esc(r['quoted'])[:180]} "
                    f"| {esc(r.get('claim_id') or '-')} "
                    f"| {esc(r['artifact'])[:160]} "
                    f"| {esc(r['artifact_value'])[:260]} "
                    f"| {esc(r['note'])} |"
                )
            add("")

    if res:
        add("## Resolutions (R-21)")
        add("")
        add("`fixed` = the sentence was rewritten in the cited file. `accepted` = the row")
        add("stands as published, for the reason given. Source: `provenance-resolutions.json`.")
        add("")
        by_id = {r["row_id"]: r for r in rows}
        for f in FILE_ORDER:
            sel = [(rid, v) for rid, v in sorted(res.items(), key=lambda kv: kv[0])
                   if by_id.get(rid, {}).get("file") == f]
            if not sel:
                continue
            add(f"### `{f}`")
            add("")
            add("| Row | Tag | Status | What was done |")
            add("|---|---|---|---|")
            for rid, v in sel:
                add(f"| {rid} | {by_id[rid]['tag']} | **{v['status']}** | {esc(v['detail'])} |")
            add("")

    return "\n".join(L) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT} ({len(OUT.read_text().splitlines())} lines)")
