#!/usr/bin/env python3
"""Render thesis/provenance-sweep.md from the frozen R-7 sweep rows.

    .venv-ft/bin/python thesis/make_provenance_sweep.py

Input is `thesis/provenance-sweep.json`, the verbatim return value of the six
R-7 audit agents (one entry per agent: its scope, how many numbers it found,
and one row per number it chose to report). The rows are frozen evidence - this
script never edits them, it only groups and formats. If a finding is later
fixed in the ledgers, record that in the FIXED table at the bottom of the
rendered doc rather than by mutating the JSON: the point of the sweep is to be
a dated audit, and an audit you can silently edit is not one.

Tags, as the agents were instructed to apply them:

  VERIFIED     the number reproduces from an artifact the agent opened
  MISLEADING   the number is right but its framing, units, denominator or
               machine attribution makes a reader draw the wrong conclusion
  CONTRADICTED an artifact exists and says something else
  UNVERIFIED   no artifact behind the number at all
"""

from __future__ import annotations

import json
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
SWEEP = HERE / "provenance-sweep.json"
OUT = HERE / "provenance-sweep.md"

TAG_ORDER = ["CONTRADICTED", "UNVERIFIED", "MISLEADING", "VERIFIED"]
FILE_ORDER = [
    "README.md",
    "RESULTS.md",
    "docs/results/part1-exploratory.md",
    "docs/results/part2-rebuild.md",
    "docs/results/part3-permanence.md",
    "docs/results/part4-end-to-end.md",
    "docs/results/part5-anticipatory.md",
    "docs/results/part6-flight.md",
]


def esc(s: str) -> str:
    """Make a free-text field safe inside a markdown table cell."""
    return " ".join(str(s).split()).replace("|", "\\|")


def render() -> str:
    data = json.loads(SWEEP.read_text())
    agents = data["agents"]
    rows = [r for a in agents for r in a["rows"]]
    tags = Counter(r["tag"] for r in rows)
    n_found = sum(a["n_numbers_found"] for a in agents)

    L: list[str] = []
    add = L.append

    add("# Provenance sweep (R-7)")
    add("")
    add("Generated by `thesis/make_provenance_sweep.py` from `thesis/provenance-sweep.json`.")
    add("Do not edit this file by hand.")
    add("")
    add("Six audit agents swept `README.md`, `RESULTS.md` and the six per-Part result")
    add("ledgers on 2026-07-21, tracing every published number back to the artifact that")
    add("produced it. Each agent was required to *open* the artifact - a number is")
    add("`VERIFIED` only against a file the agent read, never against another prose")
    add("restatement of the same claim.")
    add("")
    add(f"**{n_found} numbers examined, {len(rows)} reported.** A number that reproduced")
    add("cleanly and carried no framing problem was counted and dropped; what is tabulated")
    add("below is every defect found, plus the load-bearing numbers the agents chose to")
    add("record as verified so the headline figures have a citable provenance row.")
    add("")
    add("| Tag | Rows | Meaning |")
    add("|---|---|---|")
    add(f"| CONTRADICTED | {tags['CONTRADICTED']} | an artifact exists and says something else |")
    add(f"| UNVERIFIED | {tags['UNVERIFIED']} | no artifact behind the number at all |")
    add(f"| MISLEADING | {tags['MISLEADING']} | value right, framing/units/denominator/machine wrong |")
    add(f"| VERIFIED | {tags['VERIFIED']} | reproduces from an opened artifact |")
    add("")
    add("The three non-VERIFIED tags are the work queue. They are not equally urgent:")
    add("a CONTRADICTED number is wrong in print, a MISLEADING one is a sentence that")
    add("has to be rewritten, an UNVERIFIED one needs a re-run or a deletion.")
    add("")

    add("## Scope covered")
    add("")
    for a in agents:
        add(f"- {esc(a['scope'])[:400]}")
    add("")

    for tag in TAG_ORDER:
        sel = [r for r in rows if r["tag"] == tag]
        if not sel:
            continue
        add(f"## {tag} ({len(sel)})")
        add("")
        for f in FILE_ORDER:
            fsel = [r for r in sel if r["file"] == f]
            if not fsel:
                continue
            add(f"### `{f}`")
            add("")
            add("| Published | Claim | Artifact | What the artifact says | Finding |")
            add("|---|---|---|---|---|")
            for r in fsel:
                add(
                    f"| {esc(r['quoted'])[:180]} "
                    f"| {esc(r.get('claim_id') or '-')} "
                    f"| {esc(r['artifact'])[:160]} "
                    f"| {esc(r['artifact_value'])[:260]} "
                    f"| {esc(r['note'])} |"
                )
            add("")

    return "\n".join(L) + "\n"


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT} ({len(OUT.read_text().splitlines())} lines)")
